# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 7.x version
  - 7.0

# optionally specify a list of environments, for example to test different RDBMS
env:

# optionally set up exclutions and allowed failures in the matrix
matrix:

# execute any number of scripts before the test run, custom env's are available as variables
before_script:

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  (cd php && cp src/cmszpk-razvoj.php src/cmszpk.php && make check)

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "pbrbora@unidu.hr"

