<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'Sustav\\HTTPStatus' => '/HTTPStatus.php',
                'Sustav\\Model\\Facebook' => '/Facebook.php',
                'Sustav\\Model\\Model' => '/Model.php',
                'Sustav\\Pogled\\Pogled' => '/Pogled.php',
                'Sustav\\Pogled\\Sadrzaj' => '/Sadrzaj.php',
                'Sustav\\Postavke' => '/Postavke.php',
                'Sustav\\Upravljac\\Sesija' => '/Sesija.php',
                'Sustav\\Upravljac\\Upravljac' => '/Upravljac.php',
                'Sustav\\Upravljac\\Zahtjev' => '/Zahtjev.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . $classes[$class];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
