#=============================================================================
# Sustav za upravljanje sadržajem

#--------------- programski kod ----------------------------------------------

HTMLPUR_PHP = \
src/htmlpurifier/LICENSE \
src/htmlpurifier/standalone/HTMLPurifier/Lexer/PH5P.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/Interchange.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/ValidatorAtom.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.DefaultTextDir.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.EscapeNonASCIICharacters.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.AllowedModules.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.Disable.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.TargetNoopener.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/info.ini \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.LexerImpl.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.FlashAllowFullScreen.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.AllowImportant.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.AllowedClasses.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.EscapeInvalidTags.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.TidyLevel.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Output.TidyFormat.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.ClassUseCDATA.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.IDBlacklistRegexp.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.EscapeInvalidChildren.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.MaintainLineNumbers.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Output.FlashCompat.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.CoreModules.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.RemoveEmpty.RemoveNbsp.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.HostBlacklist.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Filter.ExtractStyleBlocks.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.IDPrefix.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Cache.DefinitionImpl.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.ColorKeywords.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.ForbiddenElements.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Output.FixInnerHTML.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.SafeScripting.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.MungeSecretKey.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.IDPrefixLocal.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.SafeIframeRegexp.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.AllowHostnameUnderscore.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.Proprietary.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.DefinitionID.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.NormalizeNewlines.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.AllowDuplicates.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.HiddenElements.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.Language.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Cache.SerializerPermissions.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.DisplayLinkURI.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.DefinitionRev.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.AggressivelyRemoveScript.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.Custom.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Cache.SerializerPath.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.DisableResources.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.Linkify.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.DefaultImageAlt.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.DefinitionRev.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.DisableExcludes.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.TargetBlank.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Filter.ExtractStyleBlocks.TidyImpl.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.DefaultInvalidImageAlt.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.XHTML.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.DisableExternal.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.SafeObject.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.DefinitionRev.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.TidyRemove.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.MungeResources.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.TargetNoreferrer.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.DirectLexLineNumberSyncInterval.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.AllowedRel.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.RemoveEmpty.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.SafeEmbed.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.ConvertDocumentToFragment.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Test.ForceNoIconv.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.AllowedAttributes.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.RemoveInvalidImg.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.RemoveProcessingInstructions.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.AllowedElements.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.AllowedProperties.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Nofollow.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.Encoding.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.ForbiddenProperties.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.AllowedComments.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.AggressivelyFixLt.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.AllowedRev.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.RemoveScriptContents.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Output.CommentScriptContents.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.AllowedFrameTargets.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.BlockWrapper.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.Munge.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.MakeAbsolute.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.AllowedCommentsRegexp.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.EnableIDNA.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Filter.ExtractStyleBlocks.Escaping.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.Host.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.RemoveEmpty.RemoveNbsp.Exceptions.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.AutoParagraph.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.DisableExternalResources.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Attr.Name.UseCDATA.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.PurifierLinkify.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.CollectErrors.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.DefinitionID.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.CustomDoctype.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.DefaultInvalidImage.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.ForbiddenClasses.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Parent.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.ForbiddenAttributes.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.AllowTricky.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.AllowedFonts.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.PurifierLinkify.DocURL.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Filter.YouTube.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Allowed.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.RemoveSpansWithoutAttributes.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.MaxImgLength.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Output.SortAttr.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.MaxImgLength.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.AllowedSchemes.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Filter.Custom.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.EnableID.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Output.Newline.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.IDBlacklist.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.LegacyEntityDecoder.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/CSS.Trusted.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Trusted.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Proprietary.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Attr.ID.HTML5.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.TidyAdd.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.SafeIframe.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/AutoFormat.RemoveEmpty.Predicate.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.DefaultScheme.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Doctype.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.OverrideAllowedSchemes.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/URI.Base.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Filter.ExtractStyleBlocks.Scope.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Strict.txt \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/Exception.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema.ser \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/InterchangeBuilder.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/Validator.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/Builder/Xml.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/Builder/ConfigSchema.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/Interchange/Directive.php \
src/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/Interchange/Id.php \
src/htmlpurifier/standalone/HTMLPurifier/Printer.php \
src/htmlpurifier/standalone/HTMLPurifier/Language/messages/en-x-test.php \
src/htmlpurifier/standalone/HTMLPurifier/Language/messages/en-x-testmini.php \
src/htmlpurifier/standalone/HTMLPurifier/Language/messages/en.php \
src/htmlpurifier/standalone/HTMLPurifier/Language/classes/en-x-test.php \
src/htmlpurifier/standalone/HTMLPurifier/Filter/ExtractStyleBlocks.php \
src/htmlpurifier/standalone/HTMLPurifier/Filter/YouTube.php \
src/htmlpurifier/standalone/HTMLPurifier/Printer/ConfigForm.css \
src/htmlpurifier/standalone/HTMLPurifier/Printer/ConfigForm.js \
src/htmlpurifier/standalone/HTMLPurifier/Printer/CSSDefinition.php \
src/htmlpurifier/standalone/HTMLPurifier/Printer/HTMLDefinition.php \
src/htmlpurifier/standalone/HTMLPurifier/Printer/ConfigForm.php \
src/htmlpurifier/standalone/HTMLPurifier/EntityLookup/entities.ser \
src/htmlpurifier/HTMLPurifier.standalone.php

SLUGGEN_PHP = \
src/sluggenerator/LICENSE \
src/sluggenerator/SlugGenerator.php \
src/sluggenerator/SlugOptions.php

ADMINER_PHP = \
adminer.php sqlite.php loginSqlite.php plugin.php

MINIFY_PHP = \
src/minify/minify/LICENSE \
src/minify/minify/data/js/keywords_after.txt \
src/minify/minify/data/js/keywords_before.txt \
src/minify/minify/data/js/keywords_reserved.txt \
src/minify/minify/data/js/operators_after.txt \
src/minify/minify/data/js/operators_before.txt \
src/minify/minify/data/js/operators.txt \
src/minify/minify/src/CSS.php \
src/minify/minify/src/Exception.php \
src/minify/minify/src/Exceptions/BasicException.php \
src/minify/minify/src/Exceptions/FileImportException.php \
src/minify/minify/src/Exceptions/IOException.php \
src/minify/minify/src/JS.php \
src/minify/minify/src/Minify.php \
src/minify/pathconv/LICENSE \
src/minify/pathconv/src/ConverterInterface.php \
src/minify/pathconv/src/Converter.php \
src/minify/pathconv/src/NoConverter.php

LIB_PHP =
LIB_RES = $(HTMLPUR_PHP) $(SLUGGEN_PHP) $(ADMINER_PHP) $(MINIFY_PHP)

#-----------------------------------------------------------------------------
